version: '3'

services:

  moderator-app:
    build: .
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.17.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/provisioning/grafana:/etc/grafana/provisioning
      - ./monitoring/grafana_data:/var/lib/grafana
    depends_on:
      - prometheus