{
 "title": "Flask Monitoring",
 "description": "Monitor Flask application through custom StatsD metrics with Prometheus and Grafana.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (flask_http_request_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (flask_http_request_total) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Classify Duration Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "classify_duration_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model Loading Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "ai_model_loading_sum", "legendFormat": "__auto" }
   ]
  }
 ]
}