name: CI Pipeline

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --deploy
        env:
          PIPENV_VENV_IN_PROJECT: 1

      - name: Override torch dependencies
        run: |
          echo "ls -lna ."
          ls -lna .
          echo "ls -lna ./.venv/"
          ls -lna ./.venv/
          ./.venv/bin/pip3 install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

      - name: Run tests
        run: ./.venv/bin/python -m unittest discover tests
